# Generated by Django 5.0 on 2024-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRAP', '0008_alter_post_hashtags_alter_post_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='AppRAP.hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(blank=True, to='AppRAP.mention'),
        ),
    ]
