# Generated by Django 4.2.10 on 2024-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRAP', '0014_chat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
