# Generated by Django 5.0 on 2024-03-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRAP', '0015_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created',
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
